Add vulnerability scanning

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -24,8 +24,34 @@ jobs:
           cache: gradle
       - name: Compile and test
         run: ./gradlew clean build
+      - name: Code vulnerability scanning
+        uses: anchore/scan-action@v3
+        id: scan
+        with:
+          path: "${{ github.workspace }}"
+          fail-build: true
+          severity-cutoff: high
+          acs-report-enable: true
+      # - name: Upload vulnerability report
+      #   uses: github/codeql-action/upload-sarif@v2
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: ${{ steps.scan.outputs.sarif }}
       - name: Package as OCI image
         run: ./gradlew bootBuildImage --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+      - name: OCI image vulnerability scanning
+        uses: anchore/scan-action@v3.2.5
+        id: scan
+        with:
+          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+          fail-build: true
+          severity-cutoff: high
+          acs-report-enable: true
+      # - name: Upload vulnerability report
+      #   uses: github/codeql-action/upload-sarif@v2
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: ${{ steps.scan.outputs.sarif }}
       - uses: docker/login-action@v2
         with:
           username: ${{ github.actor }}
